/* 
    Document   : index
    Created on : Mar 20, 2016, 2:03:43 PM
    Author     : cavaji
    
    follow     :    https://twitter.com/Cavaji
                    https://plus.google.com/u/0/109777059100477708540
                    http://cavaji.blogspot.com/
                    https://www.facebook.com/Cavaji-Soft-292268400944940/
*/
package model;
// Generated Mar 20, 2016 2:06:55 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String username;
     private String password;

    public User() {
    }

    public User(String name, String username, String password) {
       this.name = name;
       this.username = username;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


